
##################################################################################################
play:
  name: Play sound effect
  description: Play sound effect from library on LVT speaker

  fields:
    play:
      name: Sound effect name
      description: Sound effect name. Consult LVT configuration to list available sound effects
      required: true
      selector:
        text:
    importance:
      name: Message importance
      description: Respect speaker importance filter settings
      required: false
      default: "0: Common chattering"
      selector:
        select:
          options:
            - "0: Common chattering"
            - "1: Informational message"
            - "2: Important message"
            - "3: Critically important message"
    speaker:
      name: "[List of] speaker IDs"
      description: Any of LVT speaker id, HA device id, unique id, device entity id or location id are accepted
      required: false
      selector:
        device:
          integration: lvt

##################################################################################################
say:
  name: Say
  description: Say something with LVT speaker

  fields:
    say:
      name: Text to say
      description: Text to say.
      required: true
      selector:
        text:
    importance:
      name: Message importance
      description: Respect speaker importance filter settings
      required: false
      default: "0: Common chattering"
      selector:
        select:
          options:
            - "0: Common chattering"
            - "1: Informational message"
            - "2: Important message"
            - "3: Critically important message"
    speaker:
      name: List of speaker IDs
      description: Any of LVT speaker id, HA device id, unique id, device entity id or location id are accepted
      required: false
      selector:
        device:
          integration: lvt


##################################################################################################
confirm:
  name: Ask for confirmation
  description: Simple agree / disagree dialogue

  fields:
    say:
      name: Confirmation request
      description: Confirmation request text
      required: true
      selector:
        text:

    prompt:
      name: Prompt
      description: Periodical reminder awaiting user reaction
      required: false
      selector:
        text:

    ### YES
    yes_intent:
      name: YES intent name
      description: Intent name to fire if user answered positive
      required: true
      selector:
        text:

    yes_say:
      name: Positive confirmation
      description: Text to confirm positive answer
      required: false
      selector:
        text:

    ### NO
    no_intent:
      name: NO intent name
      description: Intent name to fire on negative answer
      required: true
      selector:
        text:

    no_say:
      name: Negative confirmation
      description: Text to confirm negative answer
      required: false
      selector:
        text:


    ### DEFAULT
    default_timeout:
      name: Timeout
      description: Time (seconds) to wait user answer
      required: true
      default: 30

      selector:
        number:
          min: 10
          max: 600
          unit_of_measurement: "seconds"

    default_intent:
      name: Default intent name
      description: Intent name to fire if user not answered befor timeout
      required: true
      selector:
        text:

    default_say:
      name: Cancel confirmation
      description: Text to confirm default value
      required: false
      selector:
        text:

    importance:
      name: Importance level
      description: Respect speaker importance filter settings
      required: false
      default: "0: Common chattering"
      selector:
        select:
          options:
            - "0: Common chattering"
            - "1: Informational message"
            - "2: Important message"
            - "3: Critically important message"

    speaker:
      name: List of speaker IDs
      description: Any of LVT speaker id, HA device id, unique id, device entity id or location id are accepted
      required: false
      selector:
        device:
          integration: lvt



##################################################################################################
negotiate:
  name: Negotiate
  description: Ask person to choose one of pre-defined options

  fields:
    say:
      name: Text to say
      description: Text to say.
      required: true
      selector:
        text:
    importance:
      name: Importance level
      description: Respect speaker importance filter settings
      required: false
      default: "0: Common chattering"
      selector:
        select:
          options:
            - "0: Common chattering"
            - "1: Informational message"
            - "2: Important message"
            - "3: Critically important message"
    speaker:
      name: List of speaker IDs
      description: Any of LVT speaker id, HA device id, unique id, device entity id or location id are accepted
      required: false
      selector:
        device:
          integration: lvt


    ### OPTION 1
    option_1_intent:
      name: Option 1 intent name
      description: Intent name to fire if user choose this option
      required: true
      selector:
        text:

    option_1_utterance:
      name: Option 1 utterance phrase
      description: Utterance phrase
      required: true
      selector:
        text:

    option_1_say:
      name: Option 1 choosen confirmation message
      description: Text to confirm selection of this option
      required: false
      selector:
        text:

    ### OPTION 2
    option_2_intent:
      name: Option 2 intent name
      description: Intent name to fire if user choose this option
      required: true
      selector:
        text:

    option_2_utterance:
      name: Option 2 utterance phrase
      description: Utterance phrase
      required: true
      selector:
        text:

    option_2_say:
      name: Option 2 choosen confirmation message
      description: Text to confirm selection of this option
      required: false
      selector:
        text:

    ### OPTION 3
    option_3_intent:
      name: Option 3 intent name
      description: Intent name to fire if user choose this option
      required: true
      selector:
        text:

    option_3_utterance:
      name: Option 3 utterance phrase
      description: Utterance phrase
      required: true
      selector:
        text:

    option_3_say:
      name: Option 3 choosen confirmation message
      description: Text to confirm selection of this option
      required: false
      selector:
        text:

    ### OPTION 4
    option_4_intent:
      name: Option 4 intent name
      description: Intent name to fire if user choose this option
      required: true
      selector:
        text:

    option_4_utterance:
      name: Option 4 utterance phrase
      description: Utterance phrase
      required: true
      selector:
        text:

    option_4_say:
      name: Option 4 choosen confirmation message
      description: Text to confirm selection of this option
      required: false
      selector:
        text:

    ### OPTION 1
    option_5_intent:
      name: Option 5 intent name
      description: Intent name to fire if user choose this option
      required: true
      selector:
        text:

    option_5_utterance:
      name: Option 5 utterance phrase
      description: Utterance phrase
      required: true
      selector:
        text:

    option_5_say:
      name: Option 5 choosen confirmation message
      description: Text to confirm selection of this option
      required: false
      selector:
        text:

    ### DEFAULT
    default_timeout:
      name: Timeout
      description: Time (seconds) to wait user answer
      required: true
      default: 30

      selector:
        number:
          min: 10
          max: 600
          unit_of_measurement: "seconds"

    default_intent:
      name: Default intent name
      description: Intent name to fire if user not answered befor timeout
      required: true
      selector:
        text:

    default_say:
      name: Cancel confirmation
      description: Text to confirm default value
      required: false
      selector:
        text:

##################################################################################################
restart_speaker:
  name: Restart speaker
  description: Restart speaker

  fields:
    speaker:
      name: "[List of] speaker IDs"
      description: Any of LVT speaker id, HA device id, unique id, device entity id or location id are accepted
      required: false
      selector:
        device:
          integration: lvt
    update:
      name: Force LVT client software update
      description: Update LVT client version and restart speaker
      required: false
      selector:
        boolean:
    say:
      name: Text to say before restarting speaker
      description: Say something before restarting speaker
      required: false
      selector:
        text:
    say_on_restart:
      name: Text to say after reboot
      description: Say something after speaker restarted
      required: false
      selector:
        text:

##################################################################################################
reload:
  name: Reload
  description: Reload the YAML-based LVT configuration.



